Repository thegazelle-ad/gazelle-server, pull requests merged in 2018-04, with the labels that each got.

#349 Rename authors to staff
  __tests__/end-to-end/admin-tests/login.test.js
  __tests__/end-to-end/admin-tests/serverside-rendering.test.js
  __tests__/end-to-end/admin-tests/staff-list.test.js
  __tests__/end-to-end/gazelle-tests/serverside-rendering.test.js
  __tests__/end-to-end/jest-setup.js
  migrations/20180330114037_rename-authors-to-staff.js
  src/components/admin/IssueArticleController.jsx
  src/components/admin/Navigation.jsx
  src/components/admin/Readme.jsx
  src/components/admin/SearchBar.jsx
  src/components/admin/StaffController.jsx
  src/components/admin/StaffListController.jsx
  src/components/admin/article/ArticleController.jsx
  src/components/admin/article/components/UnpublishButton.jsx
  src/components/admin/form-components/SearchableSelector.jsx
  src/components/main/AppController.jsx
  src/components/main/ArticleList.jsx
  src/components/main/Author.jsx
  src/components/main/AuthorList.jsx
  src/components/main/SearchController.jsx
  src/components/main/StaffMember.jsx
  src/components/main/StaffMemberController.jsx
  src/components/main/TeamMembersList.jsx
  src/components/main/TeamPageController.jsx
  src/lib/db.js
  src/lib/falcor/FalcorRouter.js
  src/lib/falcor/routes/articles/by-slug.js
  src/lib/falcor/routes/index.js
  src/lib/falcor/routes/search/authors.js
  src/lib/falcor/routes/search/index.js
  src/lib/falcor/routes/search/staff.js
  src/lib/falcor/routes/semesters/by-name.js
  src/lib/falcor/routes/staff/by-slug.js
  src/lib/falcor/routes/staff/index.js
  src/lib/falcor/routes/teams/by-slug.js
  src/lib/utilities.js
  src/routes/admin-routes.js
  src/routes/main-routes.js
  src/styles/abstracts/_variables.scss
  src/styles/components/_article-preview.scss
  src/styles/components/_featured-article.scss
  src/styles/components/_header.scss
  src/styles/components/_navigation.scss
  src/styles/components/_staff.scss
  src/styles/main.scss
Labels: SWE final project

#351 Add modal provider
  .babelrc
  .eslintrc.js
  __tests__/end-to-end/admin-tests/assets/checkServerRestarted.js
  __tests__/end-to-end/admin-tests/e2e-admin-utilities.js
  __tests__/end-to-end/admin-tests/header.test.js
  package-lock.json
  package.json
  src/client-scripts/admin-client.js
  src/components/admin/AppController.jsx
  src/components/admin/ArticleList.jsx
  src/components/admin/ArticleListController.jsx
  src/components/admin/ImageController.jsx
  src/components/admin/IssueArticleController.jsx
  src/components/admin/IssueCategoryController.jsx
  src/components/admin/IssueListController.jsx
  src/components/admin/Login.jsx
  src/components/admin/MainIssueController.jsx
  src/components/admin/StaffController.jsx
  src/components/admin/StaffListController.jsx
  src/components/admin/article/ArticleController.jsx
  src/components/admin/form-components/SearchableSelector.jsx
  src/components/admin/hocs/modals/Alert.jsx
  src/components/admin/hocs/modals/Confirm.jsx
  src/components/admin/hocs/modals/ModalProvider.jsx
  src/components/admin/hocs/modals/withModals.jsx
  src/lib/falcor/FalcorController.js
  src/lib/falcor/falcor-utilities.js
  src/routes/admin-routes.js
  webpack/webpack-config-generator.js
Labels: SWE final project

#357 Finish Falcor HOCs
  src/components/hocs/falcor-hocs.js
  src/components/hocs/falcor-hocs.jsx
  src/lib/falcor/__tests__/cleanupFalcorKeys.test.js
  src/lib/falcor/falcor-utilities.js
Labels: SWE final project

#361 Upgrade Falcor to v2
  package-lock.json
  package.json
  src/components/admin/ArticleListController.jsx
  src/components/admin/IssueArticleController.jsx
  src/components/admin/IssueCategoryController.jsx
  src/components/admin/IssueListController.jsx
  src/components/admin/MainIssueController.jsx
  src/components/admin/StaffController.jsx
  src/components/admin/StaffListController.jsx
  src/components/admin/article/ArticleController.jsx
  src/components/main/ArchivesController.jsx
  src/components/main/CategoryController.jsx
  src/components/main/IssueController.jsx
  src/components/main/SearchController.jsx
  src/components/main/StaffMemberController.jsx
  src/components/main/TeamPageController.jsx
  src/components/main/TextPageController.jsx
  src/lib/falcor/__tests__/cleanupFalcorKeys.test.js
  src/lib/falcor/falcor-utilities.js
  src/lib/falcor/routes/articles/by-slug.js
  src/lib/falcor/routes/issues/by-number.js
  src/lib/falcor/routes/staff/by-slug.js
  src/lib/falcor/routes/teams/by-slug.js
Labels: SWE final project

#343 Refactor of SearchBar and Added enableAdd
  src/components/admin/ArticleListController.jsx
  src/components/admin/IssueArticleController.jsx
  src/components/admin/SearchBar.jsx
  src/components/admin/StaffListController.jsx
  src/components/admin/article/ArticleController.jsx
  src/components/admin/form-components/SearchBar.jsx
  src/components/admin/form-components/SearchableSelector.jsx
  src/components/admin/form-components/searchables.jsx
  src/components/admin/form-components/withFalcorSearch.jsx
  src/lib/falcor/routes/search/articles.js
  src/lib/falcor/routes/search/index.js
  src/lib/utilities.js
Labels: SWE final project

#362 Add logger
  .babelrc
  src/client-scripts/admin-client.js
  src/client-scripts/main-client.js
  src/components/admin/hocs/modals/ModalProvider.jsx
  src/index.js
  src/lib/__tests__/logger.test.js
  src/lib/logger.js
Labels: SWE final project

#363 Add initial falcor route tests
  __tests__/config/jest.base.config.js
  package-lock.json
  package.json
  src/lib/db.js
  src/lib/falcor/routes/articles/__mocks__/database-calls.js
  src/lib/falcor/routes/articles/__tests__/__snapshots__/by-page.test.js.snap
  src/lib/falcor/routes/articles/__tests__/by-page.test.js
  src/lib/falcor/routes/articles/by-page.js
  src/lib/falcor/routes/articles/database-calls.js
  src/lib/falcor/routes/articles/index.js
Labels: SWE final project

#364 Change migrations to assume utf8
  config/database.config.example.json5
  migrations/20180325211342_migrate-posts.js
Labels: SWE final project

#368 Automate creation of test database
  .circleci/config.yml
  .circleci/scripts/load-test-database.sh
  .circleci/scripts/run-end-to-end-tests.sh
  __tests__/end-to-end/admin-tests/staff-list.test.js
  __tests__/end-to-end/gazelle-tests/serverside-rendering.test.js
  database-management/migrations/00000000000000_initialize-tables.js
  database-management/migrations/20180325204028_remove-unused-ghost-tables.js
  database-management/migrations/20180325211342_migrate-posts.js
  database-management/migrations/20180326110614_cleanup-tag-tables.js
  database-management/migrations/20180327211752_rename-author-image-column.js
  database-management/migrations/20180330105350_rename-posts-to-articles.js
  database-management/migrations/20180330114037_rename-authors-to-staff.js
  database-management/migrations/initialTables.dump
  database-management/migrations/lib/batch-insert.js
  database-management/migrations/lib/execute-dump.js
  database-management/migrations/oldPostsTables.dump
  database-management/migrations/unusedGhostTables.dump
  database-management/seeds/lib/add-article-author-relationship.js
  database-management/seeds/lib/add-article-tag-relationship.js
  database-management/seeds/lib/add-dummy-articles.js
  database-management/seeds/lib/add-dummy-categories.js
  database-management/seeds/lib/add-dummy-info-pages.js
  database-management/seeds/lib/add-dummy-issues.js
  database-management/seeds/lib/add-dummy-semesters.js
  database-management/seeds/lib/add-dummy-staff.js
  database-management/seeds/lib/add-dummy-tags.js
  database-management/seeds/lib/add-dummy-teams.js
  database-management/seeds/lib/add-issue-article-ordering.js
  database-management/seeds/lib/add-issue-category-ordering.js
  database-management/seeds/lib/add-team-staff-relationship.js
  database-management/seeds/lib/constants.js
  database-management/seeds/lib/delete-existing-data.js
  database-management/seeds/lib/index.js
  database-management/seeds/lib/utilities.js
  database-management/seeds/replace-database-with-dummy-data.js
  knexfile.js
  migrations/20180325204028_remove-unused-ghost-tables.js
  migrations/20180326110614_cleanup-tag-tables.js
  migrations/20180327211752_rename-author-image-column.js
  package.json
  scripts/circleci/fetch-test-database.sh
  scripts/circleci/helpers/get-test-database-dump.js
  scripts/circleci/load-test-database.sh
Labels: SWE final project

#369 Search bar fix
  __tests__/end-to-end/admin-tests/staff-list.test.js
  src/components/admin/form-components/withFalcorSearch.jsx
Labels: SWE final project, bug

#371 Hotfix Broken Checker from Falcor 2 Update
  src/lib/falcor/FalcorController.js
  src/lib/falcor/__tests__/expandCache.test.js
Labels: SWE final project, bug

#370 Turned the searchable selector into a HOC.
  src/components/admin/article/ArticleController.jsx
  src/components/admin/form-components/SearchableSelector.jsx
  src/components/admin/form-components/searchables.jsx
  src/components/admin/form-components/withSelector.jsx
Labels: SWE final project

#375 Add initial db tests
  .circleci/config.yml
  __tests__/helpers/db-helpers.js
  src/lib/__mocks__/db.js
  src/lib/falcor/routes/articles/__mocks__/database-calls.js
  src/lib/falcor/routes/articles/__tests__/__snapshots__/database-calls.test.js.snap
  src/lib/falcor/routes/articles/__tests__/by-page.test.js
  src/lib/falcor/routes/articles/__tests__/database-calls.test.js
  src/lib/falcor/routes/articles/by-page.js
  src/lib/falcor/routes/articles/database-calls.js
Labels: SWE final project

#378 Add post merge hook
  docs/dev-environment/setting-up-dev-environment.md
  package.json
Labels: SWE final project, enhancement

#372 Remove redundant column from database
  database-management/migrations/20180414180504_remove-duplicate-staff-team-relationship.js
  database-management/seeds/lib/add-dummy-staff.js
  database-management/seeds/replace-database-with-dummy-data.js
Labels: SWE final project

#345 Added Slug editing
  database-management/migrations/20180402170153_make-varchar-uniform.js
  src/components/admin/ArticleListController.jsx
  src/components/admin/article/ArticleController.jsx
  src/components/admin/article/components/ImageUrlField.jsx
  src/components/admin/article/components/TitleField.jsx
  src/components/admin/article/components/UnpublishButton.jsx
  src/components/admin/form-components/DirectTextField.jsx
  src/components/admin/form-components/validated-fields.jsx
  src/lib/db.js
  src/lib/falcor/routes/articles/by-id.js
  src/lib/falcor/routes/articles/by-slug.js
  src/lib/falcor/routes/articles/index.js
  src/routes/admin-routes.js
Labels: SWE final project

#376 Readme Makeover + update node version
  .circleci/config.yml
  .circleci/images/primary/Dockerfile
  .nvmrc
  docs/dev-environment/setting-up-dev-environment.md
  docs/guides/developing-end-to-end-tests.md
  src/server-code/admin-server.js
  src/server-code/main-server.js
  webpack/webpack-config-generator.js
Labels: SWE final project

#377 Add tags
  src/components/admin/article/ArticleController.jsx
  src/components/admin/form-components/searchables.jsx
  src/components/admin/form-components/withSelector.jsx
  src/index.js
  src/lib/falcor/FalcorRouter.js
  src/lib/falcor/routes/articles/by-id.js
  src/lib/falcor/routes/articles/by-slug.js
  src/lib/falcor/routes/articles/database-calls.js
  src/lib/falcor/routes/index.js
  src/lib/falcor/routes/search/database-calls.js
  src/lib/falcor/routes/search/index.js
  src/lib/falcor/routes/search/tags.js
  src/lib/falcor/routes/tags/by-slug.js
  src/lib/falcor/routes/tags/database-calls.js
  src/lib/falcor/routes/tags/index.js
  src/lib/utilities.js
Labels: SWE final project

#393 Unpublish Error Fix
  __tests__/end-to-end/admin-tests/article-unpublish.test.js
  src/components/admin/ArticleList.jsx
  src/components/admin/ArticleListController.jsx
  src/components/admin/article/ArticleController.jsx
  src/components/admin/article/components/UnpublishButton.jsx
  src/components/admin/form-components/searchables.jsx
  src/server-code/admin-server.js
Labels: SWE final project

#398 Fix 404 bug
  src/components/main/ArticleController.jsx
Labels: SWE final project

#397 Add ability to create new article from admin interface
  .eslintrc.js
  __tests__/config/jest.e2e.config.js
  __tests__/end-to-end/admin-tests/__snapshots__/article-unpublish.test.js.snap
  __tests__/end-to-end/admin-tests/article-unpublish.test.js
  __tests__/end-to-end/admin-tests/login.test.js
  database-management/seeds/lib/add-dummy-articles.js
  package-lock.json
  package.json
  src/components/admin/ArticleListController.jsx
  src/components/admin/FullPageLoadingOverlay.jsx
  src/components/admin/LoadingOverlay.jsx
  src/components/admin/StaffController.jsx
  src/components/admin/StaffListController.jsx
  src/components/admin/article/CreateArticleController.jsx
  src/components/admin/form-components/ListSelector.jsx
  src/components/admin/form-components/SearchBar.jsx
  src/components/admin/hocs/modals/Alert.jsx
  src/components/admin/hocs/modals/Confirm.jsx
  src/components/admin/hocs/modals/ModalProvider.jsx
  src/components/hocs/falcor-hocs.jsx
  src/lib/__mocks__/logger.js
  src/lib/db.js
  src/lib/error-helpers.js
  src/lib/falcor/routes/articles/__tests__/__snapshots__/by-page.test.js.snap
  src/lib/falcor/routes/articles/__tests__/__snapshots__/database-calls.test.js.snap
  src/lib/falcor/routes/articles/__tests__/__snapshots__/meta.test.js.snap
  src/lib/falcor/routes/articles/__tests__/by-page.test.js
  src/lib/falcor/routes/articles/__tests__/database-calls.test.js
  src/lib/falcor/routes/articles/__tests__/meta.test.js
  src/lib/falcor/routes/articles/by-id.js
  src/lib/falcor/routes/articles/database-calls.js
  src/lib/falcor/routes/articles/meta.js
  src/lib/falcor/routes/search/tags.js
  src/lib/falcor/routes/staff/by-id.js
  src/lib/falcor/routes/staff/by-slug.js
  src/lib/falcor/routes/staff/database-calls.js
  src/lib/falcor/routes/staff/index.js
  src/lib/falcor/routes/tags/by-id.js
  src/lib/falcor/routes/tags/by-slug.js
  src/lib/falcor/routes/tags/database-calls.js
  src/lib/falcor/routes/tags/index.js
  src/lib/higher-order-helpers.js
  src/routes/admin-helpers.js
  src/routes/admin-routes.js
Labels: SWE final project
